name = "msc-staging"
main = "./dist/server/index.js"
compatibility_date = "2024-10-15"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[[routes]]
pattern = "mrstarcity.com/*"
zone_name = "mrstarcity.com"

[[routes]]
pattern = "www.mrstarcity.com/*"
zone_name = "mrstarcity.com"

[assets]
directory = "./dist/client"

[vars]
PUBLIC_STORE_DOMAIN = "qpn3i9-mn.myshopify.com"
PUBLIC_STOREFRONT_API_TOKEN = "a12031cccd536b6a36e683b8579e3796"
PUBLIC_CHECKOUT_DOMAIN = "qpn3i9-mn.myshopify.com"
PUBLIC_STOREFRONT_ID = "1000124944"
